//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayment
    {
        public long EmployeeId { get; set; }
        public int SalaryPaid { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string PaidForMonth_Year { get; set; }
    }
}
