//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMEntities : DbContext
    {
        public SMEntities()
            : base("name=SMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DocumentTypeMaster> DocumentTypeMasters { get; set; }
        public DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public DbSet<EmployeePayment> EmployeePayments { get; set; }
        public DbSet<SocietyExpens> SocietyExpenses { get; set; }
        public DbSet<TenantDetail> TenantDetails { get; set; }
        public DbSet<UserBill> UserBills { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<UserPayment> UserPayments { get; set; }
        public DbSet<VisitorDetail> VisitorDetails { get; set; }
        public DbSet<VisitorTypesMaster> VisitorTypesMasters { get; set; }
        public DbSet<UserDocument> UserDocuments { get; set; }
    }
}
