//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocument
    {
        public long FlatNumber { get; set; }
        public long TenantId { get; set; }
        public string DocumentName { get; set; }
        public byte[] DocumentData { get; set; }
    }
}
