//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPayment
    {
        public long FlatNumber { get; set; }
        public long AmountPaid { get; set; }
        public System.DateTime PaidDate { get; set; }
        public System.TimeSpan PaidTime { get; set; }
        public string PaymentMode { get; set; }
        public string PaidForTheMonthOf { get; set; }
    
        public virtual UserPayment UserPayment1 { get; set; }
        public virtual UserPayment UserPayment2 { get; set; }
    }
}
