//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBill
    {
        public long FlatNumber { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillForMonth { get; set; }
        public string BillForYear { get; set; }
        public long Amount { get; set; }
    }
}
