//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorDetail
    {
        public long FlatNumber { get; set; }
        public string VisitorName { get; set; }
        public string VisitorAddress { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.TimeSpan VisitTime { get; set; }
        public string VisitPurpose { get; set; }
        public byte[] VisitorImage { get; set; }
        public long VisitorType { get; set; }
        public Nullable<long> EmployeeId { get; set; }
    }
}
